version: 1.0.{build}-{branch}

branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  files:
    - .drone.star
    - .github/**
    - android/**
    - docs/**
    - src/**/*_posix.*
    - src/**/*_linux.*
    - src/**/*_gnulinux.*
    - src/**/*_x11.*
    - src/**/*_gtk.*
    - src/**/*_android.*
    - src/**/*_mac.*
    - LICENSE
    - README.md

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2019

init:
  - ps: |
      If (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        $env:is_not_pr = "true"
      }
      If (-Not $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED) {
        $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED = " "
      }

install:
  - |
    vcpkg integrate remove
    xb setup

platform: Windows

configuration: Release

build_script:
  - xb build --config=%CONFIGURATION% --target=src\xenia-app

after_build:
  - 7z a xenia_%APPVEYOR_REPO_BRANCH%.zip -- LICENSE "%APPVEYOR_BUILD_FOLDER%\build\bin\%PLATFORM%\%CONFIGURATION%\xenia.exe"

artifacts:
  - path: '*.zip'